### ISSUE TITLE
numpy version causing runtime error

### ISSUE THREAD

**Issue by Bjorn-Blom** [DeNederlandscheBank/data-quality-rules#26]
Hi,

The installed version of numpy is causing a runtime error for Windows 10 users (Windows fmod() bug). See also [this link](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html). I'm getting this error in Anaconda Jupyter Notebook too, with a link to the webpage stated before.

Workaround that works for most of the people (and for me): de-install numpy and pandas, install numpy 1.19.3 and then install pandas again.

Estimated Time of Fix is somewhere in 2021.

For completeness:
If you are reporting a bug, please include:

Your operating system name and version.
Windows 10

Any details about your local setup that might be helpful in troubleshooting.
Set up with an anaconda environment with online installation as stated in the README file. Get this error both in Jupyter Notebook and Visual studio.

Detailed steps to reproduce the bug.
I got this error on each notebook where pandas is used.

![image](https://user-images.githubusercontent.com/56066778/103403885-0ea49280-4b52-11eb-9dd4-5f12b4c3a8dc.png)

**Comment by wjwillemse** [comment]
We assume that this is solved by now. If this problem persists, please reopen this issue, then we see what we can do.
