### ISSUE TITLE
pd.read_excel causes XLRDError

### ISSUE THREAD

**Issue by Bjorn-Blom** [DeNederlandscheBank/data-quality-rules#27]
Hi,

The latest version of the XLRD package only supports .xls files. Therefore the .xlsx parsed in the notebooks are causing errors. A few solutions to this can be found [here](https://exerror.com/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported/).

I suggest to implement Solution 3, which I have done locally too and it fixed the issue. I.e. installing the package openpyxl and change the python code in: pandas.read_excel(‘excel_file.xlsx’, engine=’openpyxl’).

For completeness:
If you are reporting a bug, please include:

Your operating system name and version.
Windows 10

Any details about your local setup that might be helpful in troubleshooting.
Anaconda environment set up following the online install of the README file.

Detailed steps to reproduce the bug.
Can be tested in each notebook where pd.read_excel is used. See image below.

![image](https://user-images.githubusercontent.com/56066778/103404337-6abbe680-4b53-11eb-86ad-469180e7e6b8.png)

**Comment by wjwillemse** [comment]
This issue is solved in v0.6.0
